// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: metric.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricID represents a metric identifier.
type MetricID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype         string                 `protobuf:"bytes,2,opt,name=mtype,proto3" json:"mtype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricID) Reset() {
	*x = MetricID{}
	mi := &file_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricID) ProtoMessage() {}

func (x *MetricID) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricID.ProtoReflect.Descriptor instead.
func (*MetricID) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{0}
}

func (x *MetricID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricID) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

// Metrics represents a metric with associated data.
type Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype string                 `protobuf:"bytes,2,opt,name=mtype,proto3" json:"mtype,omitempty"`
	// Optional int64 delta for counters
	Delta *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	// Optional double value for gauges
	Value         *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metrics) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

func (x *Metrics) GetDelta() *wrapperspb.Int64Value {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *Metrics) GetValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metrics) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Metrics) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request message for updating a metric.
type UpdateMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metrics               `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricRequest) Reset() {
	*x = UpdateMetricRequest{}
	mi := &file_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricRequest) ProtoMessage() {}

func (x *UpdateMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMetricRequest) GetMetric() *Metrics {
	if x != nil {
		return x.Metric
	}
	return nil
}

// Response message for update, returns updated metric.
type UpdateMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metrics               `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricResponse) Reset() {
	*x = UpdateMetricResponse{}
	mi := &file_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricResponse) ProtoMessage() {}

func (x *UpdateMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMetricResponse) GetMetric() *Metrics {
	if x != nil {
		return x.Metric
	}
	return nil
}

// Request message for getting a metric.
type GetMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *MetricID              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetricRequest) GetId() *MetricID {
	if x != nil {
		return x.Id
	}
	return nil
}

// Response message for listing all metrics.
type ListMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metrics             `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetricsResponse) Reset() {
	*x = ListMetricsResponse{}
	mi := &file_metric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetricsResponse) ProtoMessage() {}

func (x *ListMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetricsResponse.ProtoReflect.Descriptor instead.
func (*ListMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metric_proto_rawDescGZIP(), []int{5}
}

func (x *ListMetricsResponse) GetMetrics() []*Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_metric_proto protoreflect.FileDescriptor

const file_metric_proto_rawDesc = "" +
	"\n" +
	"\fmetric.proto\x12\ametrics\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"0\n" +
	"\bMetricID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05mtype\x18\x02 \x01(\tR\x05mtype\"\x8c\x02\n" +
	"\aMetrics\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05mtype\x18\x02 \x01(\tR\x05mtype\x121\n" +
	"\x05delta\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05delta\x122\n" +
	"\x05value\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"?\n" +
	"\x13UpdateMetricRequest\x12(\n" +
	"\x06metric\x18\x01 \x01(\v2\x10.metrics.MetricsR\x06metric\"@\n" +
	"\x14UpdateMetricResponse\x12(\n" +
	"\x06metric\x18\x01 \x01(\v2\x10.metrics.MetricsR\x06metric\"5\n" +
	"\x10GetMetricRequest\x12!\n" +
	"\x02id\x18\x01 \x01(\v2\x11.metrics.MetricIDR\x02id\"A\n" +
	"\x13ListMetricsResponse\x12*\n" +
	"\ametrics\x18\x01 \x03(\v2\x10.metrics.MetricsR\ametrics2\x85\x01\n" +
	"\x11MetricReadService\x122\n" +
	"\x03Get\x12\x19.metrics.GetMetricRequest\x1a\x10.metrics.Metrics\x12<\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x1c.metrics.ListMetricsResponse2[\n" +
	"\x12MetricWriteService\x12E\n" +
	"\x06Update\x12\x1c.metrics.UpdateMetricRequest\x1a\x1d.metrics.UpdateMetricResponseB.Z,github.com/sbilibin2017/gophmetrics/pkg/grpcb\x06proto3"

var (
	file_metric_proto_rawDescOnce sync.Once
	file_metric_proto_rawDescData []byte
)

func file_metric_proto_rawDescGZIP() []byte {
	file_metric_proto_rawDescOnce.Do(func() {
		file_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_proto_rawDesc), len(file_metric_proto_rawDesc)))
	})
	return file_metric_proto_rawDescData
}

var file_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metric_proto_goTypes = []any{
	(*MetricID)(nil),               // 0: metrics.MetricID
	(*Metrics)(nil),                // 1: metrics.Metrics
	(*UpdateMetricRequest)(nil),    // 2: metrics.UpdateMetricRequest
	(*UpdateMetricResponse)(nil),   // 3: metrics.UpdateMetricResponse
	(*GetMetricRequest)(nil),       // 4: metrics.GetMetricRequest
	(*ListMetricsResponse)(nil),    // 5: metrics.ListMetricsResponse
	(*wrapperspb.Int64Value)(nil),  // 6: google.protobuf.Int64Value
	(*wrapperspb.DoubleValue)(nil), // 7: google.protobuf.DoubleValue
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 9: google.protobuf.Empty
}
var file_metric_proto_depIdxs = []int32{
	6,  // 0: metrics.Metrics.delta:type_name -> google.protobuf.Int64Value
	7,  // 1: metrics.Metrics.value:type_name -> google.protobuf.DoubleValue
	8,  // 2: metrics.Metrics.created_at:type_name -> google.protobuf.Timestamp
	8,  // 3: metrics.Metrics.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: metrics.UpdateMetricRequest.metric:type_name -> metrics.Metrics
	1,  // 5: metrics.UpdateMetricResponse.metric:type_name -> metrics.Metrics
	0,  // 6: metrics.GetMetricRequest.id:type_name -> metrics.MetricID
	1,  // 7: metrics.ListMetricsResponse.metrics:type_name -> metrics.Metrics
	4,  // 8: metrics.MetricReadService.Get:input_type -> metrics.GetMetricRequest
	9,  // 9: metrics.MetricReadService.List:input_type -> google.protobuf.Empty
	2,  // 10: metrics.MetricWriteService.Update:input_type -> metrics.UpdateMetricRequest
	1,  // 11: metrics.MetricReadService.Get:output_type -> metrics.Metrics
	5,  // 12: metrics.MetricReadService.List:output_type -> metrics.ListMetricsResponse
	3,  // 13: metrics.MetricWriteService.Update:output_type -> metrics.UpdateMetricResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_metric_proto_init() }
func file_metric_proto_init() {
	if File_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_proto_rawDesc), len(file_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_metric_proto_goTypes,
		DependencyIndexes: file_metric_proto_depIdxs,
		MessageInfos:      file_metric_proto_msgTypes,
	}.Build()
	File_metric_proto = out.File
	file_metric_proto_goTypes = nil
	file_metric_proto_depIdxs = nil
}
